[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = "0.8.22"
serde_json = "1.0.140"
codesnap = { path = "../core", version = "0.10.8" }
clap = { version = "4.5.21", features = ["derive"] }

