name: Release CodeSnap to crates.io

on:
  push:
    paths:
      - core/Cargo.toml
      - lib/Cargo.toml
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Read version from core project
        id: read_toml
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: core/Cargo.toml
          field: package.version

      - uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_TOKEN }}

      - name: Publish library to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path core/Cargo.toml

      - name: Publish cli to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path cli/Cargo.toml

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.PAT }}
          custom_tag: ${{ steps.read_toml.outputs.value }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true
          token: ${{ secrets.PAT }}

